import {
  RecoveryProfile,
  RehabPlan,
  SessionRecord,
  DailyCheckIn,
  Milestone,
  WeeklySummary,
  ReminderSetting,
  UserAuth,
} from '../types';

export const mockUser: UserAuth = {
  id: 'usr_demo_123',
  email: 'alex.recovery@pravya.health',
  name: 'Alex Morgan',
  isAuthenticated: true,
};

export const mockRecoveryProfile: RecoveryProfile = {
  id: 'prof_123',
  userId: 'usr_demo_123',
  category: 'Orthopedic',
  conditionName: 'Right Ankle Fracture (Post-Cast Rehab)',
  recoveryGoal: 'Restore full range of motion and weight-bearing capability for daily walking.',
  startDate: '2026-07-25',
  followUpDate: '2026-08-22',
  providerName: 'Dr. Sarah Lin, DPT',
  hasProfessionalPlan: true,
  currentStage: 'Week 2 — In Progress',
  adherenceStreak: 5,
};

export const mockRehabPlan: RehabPlan = {
  id: 'plan_123',
  userId: 'usr_demo_123',
  title: 'Post-Cast Ankle Mobility & Range-of-Motion Plan',
  providerName: 'Dr. Sarah Lin, DPT',
  createdAt: '2026-07-25',
  updatedAt: '2026-07-25',
  activities: [
    {
      id: 'act_1',
      planId: 'plan_123',
      name: 'Ankle Alphabet Circles',
      instructions:
        'Sit comfortably with your leg elevated. Trace out letters A through Z with your big toe slowly without moving your knee.',
      durationMins: 10,
      sets: 2,
      reps: 1,
      frequency: '2x Daily',
      scheduledDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      notes: 'Keep motion smooth and painless. Pause if stiffness feels uncomfortable.',
    },
    {
      id: 'act_2',
      planId: 'plan_123',
      name: 'Seated Calf Towel Stretch',
      instructions:
        'Sit on the floor or bed with leg extended. Loop a long towel around the ball of your foot and gently pull back towards your body until you feel a gentle stretch in your calf.',
      durationMins: 12,
      sets: 3,
      reps: 1,
      frequency: 'Daily',
      scheduledDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      notes: 'Hold stretch for 30 seconds per rep. Do not bounce.',
    },
    {
      id: 'act_3',
      planId: 'plan_123',
      name: 'Seated Heel-Toe Rises',
      instructions:
        'Sit upright in a chair with feet flat on the floor. Slowly raise your heels while keeping toes grounded, hold for 2 seconds, then rock back onto heels raising toes.',
      durationMins: 8,
      sets: 3,
      reps: 12,
      frequency: 'Daily',
      scheduledDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      notes: 'Focus on symmetrical movement across both feet.',
    },
  ],
};

const todayStr = new Date().toISOString().split('T')[0];

export const mockSessions: SessionRecord[] = [
  // Today's sessions
  {
    id: 'sess_today_1',
    userId: 'usr_demo_123',
    activityId: 'act_1',
    activityName: 'Ankle Alphabet Circles',
    date: todayStr,
    durationMins: 10,
    status: 'COMPLETED',
    completedAt: `${todayStr} 09:30`,
    notes: 'Completed in morning with gentle flexibility.',
  },
  {
    id: 'sess_today_2',
    userId: 'usr_demo_123',
    activityId: 'act_2',
    activityName: 'Seated Calf Towel Stretch',
    date: todayStr,
    durationMins: 12,
    status: 'NOT_RECORDED',
    notes: 'Scheduled for afternoon.',
  },
  {
    id: 'sess_today_3',
    userId: 'usr_demo_123',
    activityId: 'act_3',
    activityName: 'Seated Heel-Toe Rises',
    date: todayStr,
    durationMins: 8,
    status: 'NOT_RECORDED',
  },

  // Past Week 2 Sessions
  {
    id: 'sess_p1',
    userId: 'usr_demo_123',
    activityId: 'act_1',
    activityName: 'Ankle Alphabet Circles',
    date: '2026-08-07',
    durationMins: 10,
    status: 'COMPLETED',
    completedAt: '2026-08-07 10:00',
  },
  {
    id: 'sess_p2',
    userId: 'usr_demo_123',
    activityId: 'act_2',
    activityName: 'Seated Calf Towel Stretch',
    date: '2026-08-07',
    durationMins: 12,
    status: 'COMPLETED',
    completedAt: '2026-08-07 16:30',
  },
  {
    id: 'sess_p3',
    userId: 'usr_demo_123',
    activityId: 'act_1',
    activityName: 'Ankle Alphabet Circles',
    date: '2026-08-06',
    durationMins: 10,
    status: 'COMPLETED',
  },
  {
    id: 'sess_p4',
    userId: 'usr_demo_123',
    activityId: 'act_2',
    activityName: 'Seated Calf Towel Stretch',
    date: '2026-08-06',
    durationMins: 12,
    status: 'COMPLETED',
  },
  {
    id: 'sess_p5',
    userId: 'usr_demo_123',
    activityId: 'act_3',
    activityName: 'Seated Heel-Toe Rises',
    date: '2026-08-05',
    durationMins: 8,
    status: 'COMPLETED',
  },
  {
    id: 'sess_p6',
    userId: 'usr_demo_123',
    activityId: 'act_1',
    activityName: 'Ankle Alphabet Circles',
    date: '2026-08-04',
    durationMins: 10,
    status: 'NOT_COMPLETED',
    notes: 'Rested leg due to general fatigue after work.',
  },

  // Week 1 Sessions
  {
    id: 'sess_w1_1',
    userId: 'usr_demo_123',
    activityId: 'act_1',
    activityName: 'Ankle Alphabet Circles',
    date: '2026-07-28',
    durationMins: 10,
    status: 'COMPLETED',
  },
  {
    id: 'sess_w1_2',
    userId: 'usr_demo_123',
    activityId: 'act_2',
    activityName: 'Seated Calf Towel Stretch',
    date: '2026-07-29',
    durationMins: 12,
    status: 'COMPLETED',
  },
  {
    id: 'sess_w1_3',
    userId: 'usr_demo_123',
    activityId: 'act_1',
    activityName: 'Ankle Alphabet Circles',
    date: '2026-07-30',
    durationMins: 10,
    status: 'COMPLETED',
  },
  {
    id: 'sess_w1_4',
    userId: 'usr_demo_123',
    activityId: 'act_3',
    activityName: 'Seated Heel-Toe Rises',
    date: '2026-07-31',
    durationMins: 8,
    status: 'COMPLETED',
  },
  {
    id: 'sess_w1_5',
    userId: 'usr_demo_123',
    activityId: 'act_2',
    activityName: 'Seated Calf Towel Stretch',
    date: '2026-08-01',
    durationMins: 12,
    status: 'NOT_COMPLETED',
  },
];

export const mockCheckIns: DailyCheckIn[] = [
  {
    id: 'chk_1',
    userId: 'usr_demo_123',
    sessionId: 'sess_today_1',
    date: todayStr,
    difficulty: 2,
    comfort: 4,
    energy: 4,
    notes: 'Felt calm and comfortable tracing the full alphabet.',
  },
  {
    id: 'chk_2',
    userId: 'usr_demo_123',
    sessionId: 'sess_p1',
    date: '2026-08-07',
    difficulty: 3,
    comfort: 4,
    energy: 3,
    notes: 'Good consistency today. Stretches felt comfortable.',
  },
  {
    id: 'chk_3',
    userId: 'usr_demo_123',
    sessionId: 'sess_p3',
    date: '2026-08-06',
    difficulty: 3,
    comfort: 3,
    energy: 4,
  },
  {
    id: 'chk_4',
    userId: 'usr_demo_123',
    sessionId: 'sess_p5',
    date: '2026-08-05',
    difficulty: 2,
    comfort: 4,
    energy: 4,
  },
  {
    id: 'chk_5',
    userId: 'usr_demo_123',
    sessionId: 'sess_w1_1',
    date: '2026-07-28',
    difficulty: 4,
    comfort: 2,
    energy: 3,
    notes: 'First day of ankle circles post-cast removal.',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: 'm_1',
    userId: 'usr_demo_123',
    title: 'Professional Plan Created',
    date: '2026-07-25',
    status: 'COMPLETED',
    description: 'Received custom post-cast rehabilitation plan from Dr. Sarah Lin, DPT.',
    type: 'PROVIDER_MILESTONE',
  },
  {
    id: 'm_2',
    userId: 'usr_demo_123',
    title: 'First Recorded Session',
    date: '2026-07-26',
    status: 'COMPLETED',
    description: 'Completed initial Ankle Alphabet Circles session as instructed.',
    type: 'FIRST_SESSION',
  },
  {
    id: 'm_3',
    userId: 'usr_demo_123',
    title: 'First Week Complete',
    date: '2026-08-01',
    status: 'COMPLETED',
    description: 'Recorded 5 planned recovery sessions during Week 1.',
    type: 'FIRST_WEEK',
    recordedSessionsAtMilestone: 5,
  },
  {
    id: 'm_4',
    userId: 'usr_demo_123',
    title: 'Adherence Milestone: 10 Sessions Recorded',
    date: '2026-08-07',
    status: 'COMPLETED',
    description: 'Reached 10 total recorded recovery sessions following professional guidelines.',
    type: 'CONSISTENCY',
    targetSessions: 10,
    recordedSessionsAtMilestone: 10,
  },
  {
    id: 'm_5',
    userId: 'usr_demo_123',
    title: 'Week 2 Completion Target',
    date: '2026-08-10',
    status: 'IN_PROGRESS',
    description: 'Complete 2 more planned sessions to fulfill Week 2 adherence goal.',
    type: 'CONSISTENCY',
    targetSessions: 12,
  },
  {
    id: 'm_6',
    userId: 'usr_demo_123',
    title: 'Doctor Follow-Up Check-In',
    date: '2026-08-22',
    status: 'UPCOMING',
    description: 'Scheduled progress evaluation with Dr. Sarah Lin, DPT.',
    type: 'PROVIDER_MILESTONE',
  },
];

export const mockWeeklySummaries: WeeklySummary[] = [
  {
    id: 'ws_1',
    userId: 'usr_demo_123',
    weekNumber: 1,
    startDate: '2026-07-25',
    endDate: '2026-07-31',
    plannedSessions: 7,
    recordedSessions: 5,
    activeDays: 4,
    milestonesReached: 3,
    checkinsCompleted: 4,
    nextMilestoneTarget: 'Continue scheduled mobility exercises in Week 2.',
    storyText:
      'You began your rehabilitation journey with clear commitment. During Week 1, you completed 5 sessions out of 7 planned, establishing your initial routine with your calf stretches and ankle circles.',
  },
  {
    id: 'ws_2',
    userId: 'usr_demo_123',
    weekNumber: 2,
    startDate: '2026-08-01',
    endDate: '2026-08-07',
    plannedSessions: 8,
    recordedSessions: 7,
    activeDays: 6,
    milestonesReached: 1,
    checkinsCompleted: 6,
    nextMilestoneTarget: 'Reach 12 total recorded sessions for Week 2 completion.',
    storyText:
      'Week 2 marked an impressive step forward in adherence. You recorded 7 sessions—2 more than last week—and reached your 10th total session milestone. Your steady consistency builds momentum for your professional plan.',
  },
];

export const mockReminders: ReminderSetting = {
  id: 'rem_123',
  userId: 'usr_demo_123',
  enabled: true,
  time: '10:00',
  frequency: 'DAILY',
};
